/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DismissalType = IDL.Variant({
  'lbw' : IDL.Null,
  'notOut' : IDL.Null,
  'runOut' : IDL.Null,
  'bowled' : IDL.Null,
  'hitWicket' : IDL.Null,
  'stumped' : IDL.Null,
  'caught' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const PlayerRole = IDL.Variant({
  'bowler' : IDL.Null,
  'allrounder' : IDL.Null,
  'wicketkeeper' : IDL.Null,
  'batsman' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MatchStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'live' : IDL.Null,
  'completed' : IDL.Null,
});
export const Match = IDL.Record({
  'id' : IDL.Nat,
  'status' : MatchStatus,
  'venue' : IDL.Text,
  'winnerId' : IDL.Opt(IDL.Nat),
  'team1Id' : IDL.Nat,
  'team2Id' : IDL.Nat,
  'tournamentId' : IDL.Nat,
  'scheduledAt' : Timestamp,
});
export const MatchScorecard = IDL.Record({
  'team1Id' : IDL.Nat,
  'team2Id' : IDL.Nat,
  'team1Score' : IDL.Nat,
  'team2Score' : IDL.Nat,
});
export const MatchDetails = IDL.Record({
  'match' : Match,
  'scorecard' : MatchScorecard,
});
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : PlayerRole,
  'jerseyNumber' : IDL.Nat,
  'teamId' : IDL.Nat,
});
export const PointsTableEntry = IDL.Record({
  'ties' : IDL.Nat,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'netRunRate' : IDL.Float64,
  'matchesPlayed' : IDL.Nat,
  'teamId' : IDL.Nat,
  'points' : IDL.Nat,
});
export const Team = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'logoUrl' : IDL.Text,
  'tournamentId' : IDL.Nat,
});
export const TournamentStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
});
export const Tournament = IDL.Record({
  'id' : IDL.Nat,
  'status' : TournamentStatus,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
});
export const TrendingPlayer = IDL.Record({
  'playerId' : IDL.Nat,
  'runs' : IDL.Nat,
  'wickets' : IDL.Nat,
  'tournamentId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBattingEntry' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Bool,
        DismissalType,
      ],
      [IDL.Nat],
      [],
    ),
  'createBowlingEntry' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Float64, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createInnings' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'createMatch' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, Timestamp, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createPlayer' : IDL.Func(
      [IDL.Nat, IDL.Text, PlayerRole, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createTeam' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createTournament' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatchDetails' : IDL.Func([IDL.Nat], [MatchDetails], ['query']),
  'getMatchesForTournament' : IDL.Func([IDL.Nat], [IDL.Vec(Match)], ['query']),
  'getPlayersForTeam' : IDL.Func([IDL.Nat], [IDL.Vec(Player)], ['query']),
  'getPointsTable' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PointsTableEntry)],
      ['query'],
    ),
  'getTeamsForTournament' : IDL.Func([IDL.Nat], [IDL.Vec(Team)], ['query']),
  'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
  'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getTrendingPlayers' : IDL.Func([], [IDL.Vec(TrendingPlayer)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTournamentName' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateTournamentStatus' : IDL.Func([IDL.Nat, TournamentStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DismissalType = IDL.Variant({
    'lbw' : IDL.Null,
    'notOut' : IDL.Null,
    'runOut' : IDL.Null,
    'bowled' : IDL.Null,
    'hitWicket' : IDL.Null,
    'stumped' : IDL.Null,
    'caught' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const PlayerRole = IDL.Variant({
    'bowler' : IDL.Null,
    'allrounder' : IDL.Null,
    'wicketkeeper' : IDL.Null,
    'batsman' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MatchStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'live' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Match = IDL.Record({
    'id' : IDL.Nat,
    'status' : MatchStatus,
    'venue' : IDL.Text,
    'winnerId' : IDL.Opt(IDL.Nat),
    'team1Id' : IDL.Nat,
    'team2Id' : IDL.Nat,
    'tournamentId' : IDL.Nat,
    'scheduledAt' : Timestamp,
  });
  const MatchScorecard = IDL.Record({
    'team1Id' : IDL.Nat,
    'team2Id' : IDL.Nat,
    'team1Score' : IDL.Nat,
    'team2Score' : IDL.Nat,
  });
  const MatchDetails = IDL.Record({
    'match' : Match,
    'scorecard' : MatchScorecard,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : PlayerRole,
    'jerseyNumber' : IDL.Nat,
    'teamId' : IDL.Nat,
  });
  const PointsTableEntry = IDL.Record({
    'ties' : IDL.Nat,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'netRunRate' : IDL.Float64,
    'matchesPlayed' : IDL.Nat,
    'teamId' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'logoUrl' : IDL.Text,
    'tournamentId' : IDL.Nat,
  });
  const TournamentStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Tournament = IDL.Record({
    'id' : IDL.Nat,
    'status' : TournamentStatus,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
  });
  const TrendingPlayer = IDL.Record({
    'playerId' : IDL.Nat,
    'runs' : IDL.Nat,
    'wickets' : IDL.Nat,
    'tournamentId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBattingEntry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Bool,
          DismissalType,
        ],
        [IDL.Nat],
        [],
      ),
    'createBowlingEntry' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Float64, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createInnings' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'createMatch' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, Timestamp, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createPlayer' : IDL.Func(
        [IDL.Nat, IDL.Text, PlayerRole, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createTeam' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createTournament' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatchDetails' : IDL.Func([IDL.Nat], [MatchDetails], ['query']),
    'getMatchesForTournament' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Match)],
        ['query'],
      ),
    'getPlayersForTeam' : IDL.Func([IDL.Nat], [IDL.Vec(Player)], ['query']),
    'getPointsTable' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PointsTableEntry)],
        ['query'],
      ),
    'getTeamsForTournament' : IDL.Func([IDL.Nat], [IDL.Vec(Team)], ['query']),
    'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
    'getTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getTrendingPlayers' : IDL.Func([], [IDL.Vec(TrendingPlayer)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTournamentName' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateTournamentStatus' : IDL.Func([IDL.Nat, TournamentStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };