/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DismissalType = { 'lbw' : null } |
  { 'notOut' : null } |
  { 'runOut' : null } |
  { 'bowled' : null } |
  { 'hitWicket' : null } |
  { 'stumped' : null } |
  { 'caught' : null };
export interface Match {
  'id' : bigint,
  'status' : MatchStatus,
  'venue' : string,
  'winnerId' : [] | [bigint],
  'team1Id' : bigint,
  'team2Id' : bigint,
  'tournamentId' : bigint,
  'scheduledAt' : Timestamp,
}
export interface MatchDetails { 'match' : Match, 'scorecard' : MatchScorecard }
export interface MatchScorecard {
  'team1Id' : bigint,
  'team2Id' : bigint,
  'team1Score' : bigint,
  'team2Score' : bigint,
}
export type MatchStatus = { 'scheduled' : null } |
  { 'live' : null } |
  { 'completed' : null };
export interface Player {
  'id' : bigint,
  'name' : string,
  'role' : PlayerRole,
  'jerseyNumber' : bigint,
  'teamId' : bigint,
}
export type PlayerRole = { 'bowler' : null } |
  { 'allrounder' : null } |
  { 'wicketkeeper' : null } |
  { 'batsman' : null };
export interface PointsTableEntry {
  'ties' : bigint,
  'wins' : bigint,
  'losses' : bigint,
  'netRunRate' : number,
  'matchesPlayed' : bigint,
  'teamId' : bigint,
  'points' : bigint,
}
export interface Team {
  'id' : bigint,
  'name' : string,
  'logoUrl' : string,
  'tournamentId' : bigint,
}
export type Timestamp = bigint;
export interface Tournament {
  'id' : bigint,
  'status' : TournamentStatus,
  'name' : string,
  'createdAt' : Timestamp,
}
export type TournamentStatus = { 'active' : null } |
  { 'completed' : null };
export interface TrendingPlayer {
  'playerId' : bigint,
  'runs' : bigint,
  'wickets' : bigint,
  'tournamentId' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBattingEntry' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, bigint, boolean, DismissalType],
    bigint
  >,
  'createBowlingEntry' : ActorMethod<
    [bigint, bigint, number, bigint, bigint, bigint],
    bigint
  >,
  'createInnings' : ActorMethod<
    [bigint, bigint, bigint, bigint, number],
    bigint
  >,
  'createMatch' : ActorMethod<
    [bigint, bigint, bigint, Timestamp, string],
    bigint
  >,
  'createPlayer' : ActorMethod<[bigint, string, PlayerRole, bigint], bigint>,
  'createTeam' : ActorMethod<[bigint, string, string], bigint>,
  'createTournament' : ActorMethod<[string], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatchDetails' : ActorMethod<[bigint], MatchDetails>,
  'getMatchesForTournament' : ActorMethod<[bigint], Array<Match>>,
  'getPlayersForTeam' : ActorMethod<[bigint], Array<Player>>,
  'getPointsTable' : ActorMethod<[bigint], Array<PointsTableEntry>>,
  'getTeamsForTournament' : ActorMethod<[bigint], Array<Team>>,
  'getTournament' : ActorMethod<[bigint], [] | [Tournament]>,
  'getTournaments' : ActorMethod<[], Array<Tournament>>,
  'getTrendingPlayers' : ActorMethod<[], Array<TrendingPlayer>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTournamentName' : ActorMethod<[bigint, string], undefined>,
  'updateTournamentStatus' : ActorMethod<[bigint, TournamentStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];