/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: bigint;
    name: string;
    role: PlayerRole;
    jerseyNumber: bigint;
    teamId: bigint;
}
export interface PointsTableEntry {
    ties: bigint;
    wins: bigint;
    losses: bigint;
    netRunRate: number;
    matchesPlayed: bigint;
    teamId: bigint;
    points: bigint;
}
export type Timestamp = bigint;
export interface MatchDetails {
    match: Match;
    scorecard: MatchScorecard;
}
export interface Tournament {
    id: bigint;
    status: TournamentStatus;
    name: string;
    createdAt: Timestamp;
}
export interface Match {
    id: bigint;
    status: MatchStatus;
    venue: string;
    winnerId?: bigint;
    team1Id: bigint;
    team2Id: bigint;
    tournamentId: bigint;
    scheduledAt: Timestamp;
}
export interface TrendingPlayer {
    playerId: bigint;
    runs: bigint;
    wickets: bigint;
    tournamentId: bigint;
}
export interface MatchScorecard {
    team1Id: bigint;
    team2Id: bigint;
    team1Score: bigint;
    team2Score: bigint;
}
export interface UserProfile {
    name: string;
    role: Role;
}
export interface Team {
    id: bigint;
    name: string;
    logoUrl: string;
    tournamentId: bigint;
}
export enum DismissalType {
    lbw = "lbw",
    notOut = "notOut",
    runOut = "runOut",
    bowled = "bowled",
    hitWicket = "hitWicket",
    stumped = "stumped",
    caught = "caught"
}
export enum MatchStatus {
    scheduled = "scheduled",
    live = "live",
    completed = "completed"
}
export enum PlayerRole {
    bowler = "bowler",
    allrounder = "allrounder",
    wicketkeeper = "wicketkeeper",
    batsman = "batsman"
}
export enum Role {
    organiser = "organiser",
    franchisee = "franchisee",
    viewer = "viewer"
}
export enum TournamentStatus {
    active = "active",
    completed = "completed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBattingEntry(inningsId: bigint, playerId: bigint, runs: bigint, balls: bigint, fours: bigint, sixes: bigint, isOut: boolean, dismissalType: DismissalType): Promise<bigint>;
    createBowlingEntry(inningsId: bigint, playerId: bigint, overs: number, maidens: bigint, runs: bigint, wickets: bigint): Promise<bigint>;
    createInnings(matchId: bigint, battingTeamId: bigint, totalRuns: bigint, totalWickets: bigint, totalOvers: number): Promise<bigint>;
    createMatch(tournamentId: bigint, team1Id: bigint, team2Id: bigint, scheduledAt: Timestamp, venue: string): Promise<bigint>;
    createPlayer(teamId: bigint, name: string, role: PlayerRole, jerseyNumber: bigint): Promise<bigint>;
    createTeam(tournamentId: bigint, name: string, logoUrl: string): Promise<bigint>;
    createTournament(name: string): Promise<bigint>;
    getCallerRole(): Promise<Role | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMatchDetails(matchId: bigint): Promise<MatchDetails>;
    getMatchesForTournament(tournamentId: bigint): Promise<Array<Match>>;
    getPlayersForTeam(teamId: bigint): Promise<Array<Player>>;
    getPointsTable(tournamentId: bigint): Promise<Array<PointsTableEntry>>;
    getTeamsForTournament(tournamentId: bigint): Promise<Array<Team>>;
    getTournament(id: bigint): Promise<Tournament | null>;
    getTournaments(): Promise<Array<Tournament>>;
    getTrendingPlayers(): Promise<Array<TrendingPlayer>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setUserRole(role: Role): Promise<void>;
    updateTournamentName(id: bigint, name: string): Promise<void>;
    updateTournamentStatus(id: bigint, status: TournamentStatus): Promise<void>;
}
import type { DismissalType as _DismissalType, Match as _Match, MatchDetails as _MatchDetails, MatchScorecard as _MatchScorecard, MatchStatus as _MatchStatus, Player as _Player, PlayerRole as _PlayerRole, Role as _Role, Timestamp as _Timestamp, Tournament as _Tournament, TournamentStatus as _TournamentStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBattingEntry(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: boolean, arg7: DismissalType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBattingEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_DismissalType_n3(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBattingEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_DismissalType_n3(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async createBowlingEntry(arg0: bigint, arg1: bigint, arg2: number, arg3: bigint, arg4: bigint, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBowlingEntry(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBowlingEntry(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createInnings(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInnings(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInnings(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createMatch(arg0: bigint, arg1: bigint, arg2: bigint, arg3: Timestamp, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createPlayer(arg0: bigint, arg1: string, arg2: PlayerRole, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayer(arg0, arg1, to_candid_PlayerRole_n5(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayer(arg0, arg1, to_candid_PlayerRole_n5(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async createTeam(arg0: bigint, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeam(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeam(arg0, arg1, arg2);
            return result;
        }
    }
    async createTournament(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTournament(arg0);
            return result;
        }
    }
    async getCallerRole(): Promise<Role | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerRole();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerRole();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchDetails(arg0: bigint): Promise<MatchDetails> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchDetails(arg0);
                return from_candid_MatchDetails_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchDetails(arg0);
            return from_candid_MatchDetails_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchesForTournament(arg0: bigint): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchesForTournament(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchesForTournament(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayersForTeam(arg0: bigint): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayersForTeam(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayersForTeam(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPointsTable(arg0: bigint): Promise<Array<PointsTableEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPointsTable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPointsTable(arg0);
            return result;
        }
    }
    async getTeamsForTournament(arg0: bigint): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamsForTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamsForTournament(arg0);
            return result;
        }
    }
    async getTournament(arg0: bigint): Promise<Tournament | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournament(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournament(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournaments(): Promise<Array<Tournament>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournaments();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournaments();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingPlayers(): Promise<Array<TrendingPlayer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingPlayers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingPlayers();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setUserRole(arg0: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserRole(to_candid_Role_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserRole(to_candid_Role_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTournamentName(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTournamentName(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTournamentName(arg0, arg1);
            return result;
        }
    }
    async updateTournamentStatus(arg0: bigint, arg1: TournamentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTournamentStatus(arg0, to_candid_TournamentStatus_n38(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTournamentStatus(arg0, to_candid_TournamentStatus_n38(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_MatchDetails_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchDetails): MatchDetails {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerRole): PlayerRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentStatus): TournamentStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Tournament_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tournament): Tournament {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tournament]): Tournament | null {
    return value.length === 0 ? null : from_candid_Tournament_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Role]): Role | null {
    return value.length === 0 ? null : from_candid_Role_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _Role;
}): {
    name: string;
    role: Role;
} {
    return {
        name: value.name,
        role: from_candid_Role_n8(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    match: _Match;
    scorecard: _MatchScorecard;
}): {
    match: Match;
    scorecard: MatchScorecard;
} {
    return {
        match: from_candid_Match_n17(_uploadFile, _downloadFile, value.match),
        scorecard: value.scorecard
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _MatchStatus;
    venue: string;
    winnerId: [] | [bigint];
    team1Id: bigint;
    team2Id: bigint;
    tournamentId: bigint;
    scheduledAt: _Timestamp;
}): {
    id: bigint;
    status: MatchStatus;
    venue: string;
    winnerId?: bigint;
    team1Id: bigint;
    team2Id: bigint;
    tournamentId: bigint;
    scheduledAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_MatchStatus_n19(_uploadFile, _downloadFile, value.status),
        venue: value.venue,
        winnerId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.winnerId)),
        team1Id: value.team1Id,
        team2Id: value.team2Id,
        tournamentId: value.tournamentId,
        scheduledAt: value.scheduledAt
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    role: _PlayerRole;
    jerseyNumber: bigint;
    teamId: bigint;
}): {
    id: bigint;
    name: string;
    role: PlayerRole;
    jerseyNumber: bigint;
    teamId: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_PlayerRole_n26(_uploadFile, _downloadFile, value.role),
        jerseyNumber: value.jerseyNumber,
        teamId: value.teamId
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TournamentStatus;
    name: string;
    createdAt: _Timestamp;
}): {
    id: bigint;
    status: TournamentStatus;
    name: string;
    createdAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_TournamentStatus_n31(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    live: null;
} | {
    completed: null;
}): MatchStatus {
    return "scheduled" in value ? MatchStatus.scheduled : "live" in value ? MatchStatus.live : "completed" in value ? MatchStatus.completed : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bowler: null;
} | {
    allrounder: null;
} | {
    wicketkeeper: null;
} | {
    batsman: null;
}): PlayerRole {
    return "bowler" in value ? PlayerRole.bowler : "allrounder" in value ? PlayerRole.allrounder : "wicketkeeper" in value ? PlayerRole.wicketkeeper : "batsman" in value ? PlayerRole.batsman : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
}): TournamentStatus {
    return "active" in value ? TournamentStatus.active : "completed" in value ? TournamentStatus.completed : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    organiser: null;
} | {
    franchisee: null;
} | {
    viewer: null;
}): Role {
    return "organiser" in value ? Role.organiser : "franchisee" in value ? Role.franchisee : "viewer" in value ? Role.viewer : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tournament>): Array<Tournament> {
    return value.map((x)=>from_candid_Tournament_n29(_uploadFile, _downloadFile, x));
}
function to_candid_DismissalType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DismissalType): _DismissalType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_PlayerRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerRole): _PlayerRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_TournamentStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentStatus): _TournamentStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: Role;
}): {
    name: string;
    role: _Role;
} {
    return {
        name: value.name,
        role: to_candid_Role_n36(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    organiser: null;
} | {
    franchisee: null;
} | {
    viewer: null;
} {
    return value == Role.organiser ? {
        organiser: null
    } : value == Role.franchisee ? {
        franchisee: null
    } : value == Role.viewer ? {
        viewer: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentStatus): {
    active: null;
} | {
    completed: null;
} {
    return value == TournamentStatus.active ? {
        active: null
    } : value == TournamentStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DismissalType): {
    lbw: null;
} | {
    notOut: null;
} | {
    runOut: null;
} | {
    bowled: null;
} | {
    hitWicket: null;
} | {
    stumped: null;
} | {
    caught: null;
} {
    return value == DismissalType.lbw ? {
        lbw: null
    } : value == DismissalType.notOut ? {
        notOut: null
    } : value == DismissalType.runOut ? {
        runOut: null
    } : value == DismissalType.bowled ? {
        bowled: null
    } : value == DismissalType.hitWicket ? {
        hitWicket: null
    } : value == DismissalType.stumped ? {
        stumped: null
    } : value == DismissalType.caught ? {
        caught: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerRole): {
    bowler: null;
} | {
    allrounder: null;
} | {
    wicketkeeper: null;
} | {
    batsman: null;
} {
    return value == PlayerRole.bowler ? {
        bowler: null
    } : value == PlayerRole.allrounder ? {
        allrounder: null
    } : value == PlayerRole.wicketkeeper ? {
        wicketkeeper: null
    } : value == PlayerRole.batsman ? {
        batsman: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
